# Phase 2 — Data cleaning

# Set up libraries

In [22]:
import pandas as pd
import numpy as np

# Set pandas display options for better visibility of DataFrames
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

# Load datasets from Excel file

In [25]:
df1 = pd.read_excel("../data/raw/online_retail_II.xlsx", sheet_name="Year 2009-2010")
print(f"year_2009_2010: {df1.shape[0]} rows, {df1.shape[1]} columns")
display(df1.head(5))

year_2009_2010: 525461 rows, 8 columns

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [26]:
df2 = pd.read_excel("../data/raw/online_retail_II.xlsx", sheet_name="Year 2010-2011")
print(f"year_2010_2011: {df2.shape[0]} rows, {df2.shape[1]} columns")
display(df2.head(5))

year_2010_2011: 541910 rows, 8 columns

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# Appending both the tables

In [27]:
retail_transactions = pd.concat([df1, df2], ignore_index=True)
print(f"retail_transactions: {retail_transactions.shape[0]} rows, {retail_transactions.shape[1]} columns")
display(retail_transactions.head(5))

retail_transactions: 1067371 rows, 8 columns

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# Creating a copy of the raw table

In [28]:
df = retail_transactions.copy(deep=True)

In [29]:
# Display the DataFrame
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [30]:
# Display the DataFrame information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

# 1. Header Cleaning

In [31]:
print(df.columns.to_list())

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print("FIX APPLIED: Column names have been standardized to lowercase with underscores instead of spaces.")
print(df.columns.to_list())

['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']
FIX APPLIED: Column names have been standardized to lowercase with underscores instead of spaces.
['invoice', 'stockcode', 'description', 'quantity', 'invoicedate', 'price', 'customer_id', 'country']

# 2. Standardize data types

In [34]:
df["invoice"] = df["invoice"].astype(str)

df["stockcode"] = df["stockcode"].astype(str)

df["description"] = df["description"].astype(str)

df["customer_id"] = df["customer_id"].astype("Int64")

print("Data types changed")
df.info()

Data types changed
<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   invoice      1067371 non-null  str
 1   stockcode    1067371 non-null  str
 2   description  1062989 non-null  str
 3   quantity     1067371 non-null  int64
 4   invoicedate  1067371 non-null  datetime64[us]
 5   price        1067371 non-null  float64
 6   customer_id  824364 non-null   Int64
 7   country      1067371 non-null  str
dtypes: Int64(1), datetime64[us](1), float64(1), int64(1), str(4)
memory usage: 66.2 MB

# 3. Removing whitespace

In [35]:
df["description"] = df["description"].str.strip()

# 4. Adding flags

In [36]:
df["is_cancellation"] = df["invoice"].str.startswith("C", na=False)

In [37]:
# StockCodes in Online Retail II that represent non-product line items
NON_PRODUCT_CODES = {
    "POST", "DOT", "M", "m", "D", "C2", "BANK CHARGES",
    "AMAZONFEE", "CRUK", "PADS", "S", "B", "ADJUST", "ADJUST2",
}

In [39]:
df["is_non_product"] = df["stockcode"].isin(NON_PRODUCT_CODES)

In [40]:
df["is_missing_customer"] = df["customer_id"].isna()

In [41]:
df["is_customer_cancellation"] = df["is_cancellation"] & df["customer_id"].notna()

# 5. Dropping duplicates, impossible columns, etc

In [42]:
# Drop exact duplicate rows, keeping the last occurrence
before = len(df)
df = df.drop_duplicates(keep='last').reset_index(drop=True)
print(f"Dropped {before - len(df):,} exact duplicate rows")

Dropped 34,335 exact duplicate rows

In [43]:
# Drop rows with zero information: no Description, no Customer ID, Price == 0

zero_info_mask = (df["description"].isna() & df["customer_id"].isna() & (df["price"] == 0))
print(f"Dropping {zero_info_mask.sum():,} zero-information rows "
          f"(no Description, no Customer ID, Price == 0)")
df = df[~zero_info_mask].reset_index(drop=True)

Dropping 4,275 zero-information rows (no Description, no Customer ID, Price == 0)

In [44]:
# Stock adjustment descriptions that are known to be junk or non-informative

ADJUSTMENT_DESCRIPTIONS = {
    "lost", "missing", "smashed", "check", "short", "damages",
    "damaged", "found", "thrown away", "wet", "crushed",
}

In [45]:
# stock adjustment: NOT a cancellation, negative qty, price == 0,
# and either missing description or a known junk description

junk_desc_mask = df["description"].str.lower().isin(ADJUSTMENT_DESCRIPTIONS)
df["is_stock_adjustment"] = (
        (~df["is_cancellation"])
        & (df["quantity"] < 0)
        & (df["price"] == 0)
        & (df["description"].isna() | junk_desc_mask))

In [46]:
# Display the cleaned and validated DataFrame
df

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,is_cancellation,is_non_product,is_missing_customer,is_customer_cancellation,is_stock_adjustment
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,False,False,False,False,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,False,False,False,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,False,False,False,False,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,False,False,False,False,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1028756,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,False,False,False,False,False
1028757,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,False,False,False,False,False
1028758,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,False,False,False,False,False
1028759,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,False,False,False,False,False
1028760,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680,France,False,True,False,False,False

# Exporting the cleaned dataset to the interim folder

In [47]:
df.to_csv("../data/interim/cleaned_retail_transactions.csv", index=False)